### ISSUE TITLE
TLS connection error

### ISSUE THREAD

**Issue by acwh0110** [VIDA-NYU/ache#308]
When trying to git clone (in Ubuntu):

```
error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
error: 5357 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

**Comment by aecio** [comment]
If you received this error while running the `git clone` command, the problem was not in ACHE but with either git, GitHub, or your internet connection. See e.g. the following link for some debugging directions: https://stackoverflow.com/questions/66366582/github-unexpected-disconnect-while-reading-sideband-packet
