### ISSUE TITLE
ACHE fails do download some https links

### ISSUE THREAD

**Issue by aecio** [ViDA-NYU/ache#95]
ACHE fails to download some links using `https` protocol and throws exceptions like: `javax.net.ssl.SSLHandshakeException` and `javax.net.ssl.SSLProtocolException`.

**Comment by maqzi** [comment]
These exceptions are raised when the server is configured to use strong key exchanges e.g. `ECDHE_RSA with P-256`, and a strong cipher e.g. `AES_256_GCM`. Because Java 8 out of the box doesn't support these keys and ciphers, [Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy](http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html) files need to be used.

**Steps**
* Download the files and instructions.
* Locate the `/jre/lib/security` for the Java instance that the Ache is using. For example, this location might be: `/usr/lib/jvm/java-8-oracle/jre/lib/security`.
* Remove the following .jar files from this directory: `local_policy.jar` and `US_export_policy.jar`.
* Replace these two files with the .jar files included in the JCE Unlimited Strength Jurisdiction Policy Files download.
* Stop and restart Ache.

**Comment by aecio** [comment]
This Oracle extension fixes the `javax.net.ssl.SSLHandshakeException` or the `javax.net.ssl.SSLProtocolException`?

**Comment by maqzi** [comment]
Another solution for `javax.net.ssl.SSLHandshakeException` would be to use [openJDK 8](http://openjdk.java.net/projects/jdk8/) as it comes with 256 bit ciphers out of the box.

**Comment by aecio** [comment]
I'm closing this issue now, since it is not exactly a bug in the crawler code:
* `javax.net.ssl.SSLHandshakeException : handshake_failure` is caused by the lack of some ciphers on the JVM, and can be worked around by installing the JCE extension for the Oracle JVM, or by using a recent Open JDK distribution which ships with more ciphers out-of-the-box. ACHE's docker image is built upon Open JDK, so it should not have this problem.
* `javax.net.ssl.SSLProtocolException : unrecognized_name` is a problem caused by web servers configured incorrectly. Disabling the JDK SNI extension (`-Djsse.enableSNIExtension=false`) may be a workaround, but may cause problems to other virtual servers as a side effect.

A description of these errors was also added to FAQ in ACHE's documentation:
* http://ache.readthedocs.io/en/latest/faq.html#why-am-i-getting-a-ssl-handshake-exception-for-some-sites
* http://ache.readthedocs.io/en/latest/faq.html#why-am-i-getting-a-ssl-protocol-exception-for-some-sites
